[package]
name = "rust-blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
secp256k1 = { version = "0.30.0", features = ["hashes", "rand"] }
sha2 = "0.10"
ripemd = "0.1.3"
bs58 = "0.5.1"
hex = "0.4.3"